# refresh-counts.yml
---
- name: Restart Celery
  hosts: "{{ galaxy_hosts_celery }}" 
  become: yes
  tasks:
    - service: name=supervisord state=restarted

- name: Refresh role count
  hosts: "{{ galaxy_hosts_celery }}" 
  become: yes
  tasks:  
    - name: Start the refresh        
      shell: galaxy-manage refresh_role_counts
      register: out
      when: ec2_tag_galaxy_celery_queue == 'admin'
    - debug: var=out.stdout_lines
      when: ec2_tag_galaxy_celery_queue == 'admin'

- name: Rebuild Indexes
  hosts: "{{ galaxy_hosts_web }}"
  become: yes
  tasks:  
    - name: Rebuild Custom Indexes
      shell: galaxy-manage rebuild_galaxy_indexes
      when: inventory_hostname == groups[galaxy_hosts_web][0]
    - name: Rebuild Index
      shell: galaxy-manage rebuild_index --noinput
      when: inventory_hostname == groups[galaxy_hosts_web][0]

- name: Notify slack
  hosts: 127.0.0.1 
  connection: local
  vars:
      slack_message: "{{ galaxy_slack_message | default('None') }}"
  roles:
      - role: notify-slack
        notify_slack_message: "{{ slack_message }}"
        when: slack_message != 'None'

