version: "2"
settings:
  save_conductor_container: false
  vars_files:
  - develop.yml

  conductor:
    volumes:
      - build:/build

services:

  gulp:
    from: centos:7
    roles:
      - gulp-role
    command: [/bin/true]
    working_dir: /galaxy
    user: gulp
    volumes:
      - ${PWD}:/galaxy:z
    dev_overrides:
      command: [/usr/local/bin/dumb-init, /usr/bin/gulp]

  nginx:
    from: 'centos:7'
    ports:
    - 8000:8000
    user: 'nginx'
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
    links:
      - django
    roles:
      - role: nginx
        ASSET_PATHS:
          - /build/static
        PROXY: yes
        PROXY_PASS: 'http://django:8080'
    dev_overrides:
      ports: []
      command:  [/bin/true]

  django:
    from: centos:7
    working_dir: /galaxy
    links:
      - postgres
      - elastic
      - memcache
      - rabbit
    command: [/usr/local/bin/dumb-init, /setup/start-development.sh]
    user: django
    ports:
      - "8000:8000"
    environment: 
      - C_FORCE_ROOT=1
    dev_overrides:
      volumes:
        - ${PWD}:/galaxy:z
    roles:
      - django-role

  postgres:
    from: postgres:9.5.4
    environment:
      - POSTGRES_PASSWORD={{ galaxy_postgres_password }}
      - POSTGRES_USER={{ galaxy_postgres_user }}
      - POSTGRES_DB={{ galaxy_postgres_db }} 

  elastic:
    from: elasticsearch:2.4.1

  memcache:
    from: memcached:latest

  rabbit:
    from: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER={{ galaxy_rabbitmq_user }}
      - RABBITMQ_DEFAULT_PASS={{ galaxy_rabbitmq_pass }}
      - RABBITMQ_DEFAULT_VHOST={{ galaxy_rabbitmq_vhost }}

volumes:
  build:
    docker: {}

registries: {}
