[flake8]
# E221 - Multiple spaces after operator
# E225 - Missing whitespace around operator
# E231 - Missing whitespace after ','
# E241 - Multiple spaces after ','
# E251 - Unexpected spaces around keyword / parameter equals
# E261 - At least two spaces before inline comment
# E302 - Expected 2 blank lines found 0
# E303 - Too many blank lines
# E501 - Line too long
# W391 - Blank line at end of file
# W293 - Blank line contains whitespace
# E731 - Prefer def over lambda
ignore=E221,E225,E231,E241,E251,E261,E265,E302,E303,E501,W391,W293,E731
exclude=config,galaxy/*/migrations,galaxy/*/south_migrations,galaxy/static,provisioning
