- name: Configure galaxy/public/static directory
  file:
    path: /var/lib/galaxy/public/static
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy apache configuration file
  template:
    src: galaxy.conf.j2
    dest: /etc/httpd/conf.d/galaxy.conf

- name: Collect galaxy static files
  command: galaxy-manage collectstatic --clear --noinput
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'
  notify:
    - restart apache

