- name: Configure galaxy/public/static directory
  file:
    path: /var/lib/galaxy/public/static
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy apache configuration file
  template:
    src: galaxy.conf.j2
    dest: /etc/httpd/conf.d/galaxy.conf

- name: Collect galaxy static files
  command: galaxy-manage collectstatic --clear --noinput
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'

- name: Copy wsgi.py
  copy:
    src: /usr/lib/python2.7/site-packages/galaxy/wsgi.py
    dest: /var/lib/galaxy/wsgi.py
    remote_src: yes

- name: Copy favicon.ico
  copy:
    src: /var/lib/galaxy/public/static/img/favicon-32x32.png
    dest: /var/lib/galaxy/favicon.ico
    remote_src: yes

- name: Stop apache
  service: 
    name: httpd
    state: stopped

- name: Set log file ownership
  file:
    path: '/var/log/galaxy/{{ item }}'
    owner: apache
    group: apache
    state: touch
  with_items:
  - allauth.log
  - django.log
  - galaxy.log

- name: Start apache 
  service:
    name: httpd
    state: started
    enabled: yes
