- name: Install epel
  yum: name=epel-release

- name: Install nodejs
  shell: curl -sL https://rpm.nodesource.com/setup_8.x | bash - && yum install -y nodejs

- name: Install yarn repository
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: Install yarn
  yum: name=yarn

- name: Check node version
  command: node -v

- name: Create gulp group
  group:
    name: gulp 
    gid: 1001
    state: present

- name: Create gulp user
  user:
    name: gulp 
    uid: 1000
    group: root
    groups: gulp
    append: yes
    state: present
    shell: /bin/bash 

- name: Download dumb-init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/local/bin/dumb-init
    owner: root
    group: root
    mode: 0775

- name: Create node_modules
  file:
    path: /galaxy/node_modules
    state: directory
    owner: gulp
    group: gulp
    mode: 0775

- name: Install node packages
  command: yarn global add gulp

- name: Install dependencies
  command: yarn install
  args:
    chdir: /galaxy

- name: Build static assets
  command: gulp build
  args:
    chdir: /galaxy
