- name: determine if selinux is installed
  shell: which getenforce || exit 0
  register: selinux_installed
  changed_when: false

- name: determine if selinux is enabled
  shell: getenforce | grep -q Disabled || echo yes
  register: selinux_enabled
  when: selinux_installed.stdout != ""
  ignore_errors: true
  changed_when: false

- name: set selinux booleans for Galaxy
  seboolean: name={{item}} state=yes persistent=yes
  with_items:
  - httpd_can_network_memcache
  - httpd_can_network_connect_db
  - httpd_can_sendmail
