---
- name: Manage Galaxy Container Images
  block:
    - name: Export Docker web image if it isnt local and there isnt a registry defined
      shell: "docker image save {{ galaxy_image }}:{{ galaxy_version }} | gzip >{{ galaxy_local_base_config_path | default('/tmp') }}/{{ galaxy_image }}_{{ galaxy_version }}.tgz" 
      when: inventory_hostname != "localhost" and docker_registry is not defined
      delegate_to: localhost
      tags:
      - start      

    - name: Authenticate with Docker registry if registry password given
      docker_login:
        registry: "{{ docker_registry }}"
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes
      when: docker_registry is defined and docker_registry_password is defined
      delegate_to: localhost
      tags:
      - start      

    - name: Set docker base path
      set_fact:
        docker_deploy_base_path: "{{ galaxy_base_path | default('/tmp') }}/docker_deploy"
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start      

    - name: Ensure directory exists
      file:
        path: "{{ docker_deploy_base_path }}"
        state: directory
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start      

    - name: Copy image to docker execution
      synchronize:
        src: "{{ galaxy_local_base_config_path | default('/tmp') }}/{{ galaxy_image }}_{{ galaxy_version }}.tgz"
        dest: "{{ docker_deploy_base_path }}/{{ galaxy_image }}_{{ galaxy_version }}.tgz"
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start

    - name: Remove the .tar file
      file:
        state: absent
        path: '{{ docker_deploy_base_path }}/{{ galaxy_image }}_{{ galaxy_version }}.tar'
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start
   
    - name: Unzip the archive
      shell: gunzip "{{ docker_deploy_base_path }}/{{ galaxy_image }}_{{ galaxy_version }}.tgz"
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start

    - name: Load image
      docker_image:
        name: "{{ galaxy_image }}"
        tag: "{{ galaxy_version }}"
        load_path: "{{ docker_deploy_base_path }}/{{ galaxy_image }}_{{ galaxy_version }}.tar"
        timeout: 300
      when: ansible_connection != "local" and docker_registry is not defined
      tags:
      - start      

    - include_tasks: image_push.yml
      when: docker_registry is defined and dockerhub_base is not defined
       
    - name: Set full image path for local install
      set_fact:
        galaxy_actual_image: "{{ galaxy_image }}:{{ galaxy_version }}"
      when: docker_registry is not defined
      tags:
      - start
      - stop
  when: dockerhub_base is not defined

- name: Set DockerHub Image Paths
  set_fact:
    galaxy_actual_image: "{{ dockerhub_base }}/galaxy:{{ dockerhub_version }}"
  when: dockerhub_base is defined
  tags:
  - start
  - stop

- name: Create a temp directory
  tempfile:
    state: directory
    prefix: galaxy
  register: tempdir
  tags:
  - start
  - stop

- name: Template compose file
  template:
    src: compose.yml.j2
    dest: '{{ tempdir.path }}/docker-compose.yml'
  tags:
  - start
  - stop

- name: Start galaxy
  include_tasks: start.yml
  tags:
  - start
  
- name: Stop galaxy
  include_tasks: stop.yml
  tags:
  - stop

- name: Remove temp directory
  file:
    state: absent
    path: '{{ tempdir.path }}'
  tags:
  - start
  - stop
