# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20180328_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='travis_build_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='travis_status_url',
        ),
    ]
