# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 19:26
from __future__ import unicode_literals

from django.db import migrations

ALTER_CUSTOMUSER = """
ALTER TABLE accounts_customuser DROP COLUMN github_user CASCADE
"""

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_issue_tracker_url'),
        ('accounts', '0005_github_attrs'),
    ]

    operations = [
        migrations.RunSQL(
            sql=ALTER_CUSTOMUSER
        ),
    ]
