# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0091_remove_customuser_github_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='name',
            field=models.CharField(
                choices=[
                    ('apb', 'Ansible Playbook Bundle'),
                    ('role', 'Role'),
                    ('module', 'Module'),
                    ('module_utils', 'Module Utils'),
                    ('action_plugin', 'Action Plugin'),
                    ('cache_plugin', 'Cache Plugin'),
                    ('callback_plugin', 'Callback Plugin'),
                    ('cliconf_plugin', 'CLI Conf Plugin'),
                    ('connection_plugin', 'Connection Plugin'),
                    ('filter_plugin', 'Filter Plugin'),
                    ('inventory_plugin', 'Inventory Plugin'),
                    ('lookup_plugin', 'Lookup Plugin'),
                    ('netconf_plugin', 'Netconf Plugin'),
                    ('shell_plugin', 'Shell Plugin'),
                    ('strategy_plugin', 'Strategy Plugin'),
                    ('terminal_plugin', 'Terminal Plugin'),
                    ('test_plugin', 'Test Plugin')
                ], db_index=True, max_length=512, unique=True),
        ),
    ]
