# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtask',
            name='repository_alt_name',
        ),
    ]
