# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import galaxy.main.fields

STRIP_VERSION_SUFFIX = """
UPDATE main_repositoryversion
SET version = substring(version from 2)
WHERE version ILIKE 'v%'
"""


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_repository_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryversion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='repositoryversion',
            name='description',
        ),
        migrations.AlterField(
            model_name='repositoryversion',
            name='name',
            field=galaxy.main.fields.VersionField(max_length=64),
        ),
        migrations.RenameField(
            model_name='repositoryversion',
            old_name='name',
            new_name='version',
        ),
        migrations.AlterField(
            model_name='repositoryversion',
            name='loose_version',
            field=models.CharField(max_length=64),
        ),
        migrations.RenameField(
            model_name='repositoryversion',
            old_name='loose_version',
            new_name='raw_version',
        ),
        migrations.RunSQL(
            sql=STRIP_VERSION_SUFFIX,
        ),
        migrations.AlterUniqueTogether(
            name='repositoryversion',
            unique_together={('repository', 'version')},
        ),
        migrations.AlterModelOptions(
            name='repositoryversion',
            options={'ordering': ('-version',)},
        ),
    ]
