# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('main', '0108_sanitize_namespace_names')]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={
                'ordering': ['namespace', 'repository', 'name', 'content_type']
            },
        ),
        migrations.AlterModelOptions(name='repositoryversion', options={}),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={
                ('namespace', 'repository', 'name', 'content_type')
            },
        ),
    ]
