# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_revert_sanitize_namespace_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
