# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20180817_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='community_score',
            field=models.FloatField(null=True),
        ),
    ]
