# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 14:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import galaxy.main.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_repository_community_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(
                    choices=[('search', 'Search')], max_length=30)),
                ('event_data',
                 django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=(models.Model, galaxy.main.mixins.DirtyMixin),
        ),
        migrations.CreateModel(
            name='SessionIdentifier',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4,
                                                editable=False,
                                                primary_key=True,
                                                serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, galaxy.main.mixins.DirtyMixin),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='session_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='main.SessionIdentifier'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionevent',
            unique_together=set([('session_id', 'created', 'event_type')]),
        ),
    ]
