# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_scoring_edits_remove_contentrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='quality_score_date',
            field=models.DateTimeField(null=True,
                                       verbose_name=b'DateTime last scored'),
        ),
    ]
