# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 17:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import galaxy.main.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181018_1248'),
        ('main', '0120_repository_quality_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField(default=({b'notify_author_release': True, b'notify_content_release': True, b'notify_galaxy_announce': True, b'notify_import_fail': True, b'notify_import_success': False, b'notify_survey': False},))),
                ('namespaces_followed', models.ManyToManyField(blank=True, to='main.Namespace')),
                ('repositories_followed', models.ManyToManyField(blank=True, to='main.Repository')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, galaxy.main.mixins.DirtyMixin),
        ),
    ]
