# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_auto_20181015_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtaskmessage',
            name='message_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='importtaskmessage',
            name='rule_desc',
            field=models.TextField(null=True),
        ),
    ]
