# Generated by Django 2.1.5 on 2019-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_import_task_collection_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='community_survey_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='community_score',
            field=models.FloatField(null=True),
        ),
    ]
