# Generated by Django 2.1.7 on 2019-04-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_update_contenttype'),
    ]

    operations = [
        migrations.RenameModel('CommunitySurvey', 'RepositorySurvey')
    ]
