# Generated by Django 2.1.7 on 2019-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_drop_importtask_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionversion',
            name='readme_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionversion',
            name='readme_mimetype',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='collectionversion',
            name='readme_text',
            field=models.TextField(blank=True),
        ),
    ]
