# Generated by Django 2.1.7 on 2019-05-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_collection_version_readme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='collection',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='main.Collection'),
        ),
    ]
