- name: Apply migrations
  shell: galaxy-manage migrate --fake-initial --noinput
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'

- name: Rebuild Search Indexes
  shell: "galaxy-manage rebuild_index --noinput"
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'

- name: Rebuild custom search indexes
  shell: "galaxy-manage rebuild_galaxy_indexes"
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'

- name: Create download cache table
  shell: "galaxy-manage createcachetable"
  environment:
    DJANGO_SETTINGS_MODULE: 'galaxy.settings.custom'
