{
 "title": "Galaxy Search Metrics - Prometheus",
 "time": { "from": "now/w", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 keywords for the past week",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, search_criteria{ctype=\"keyword\"})"
    }
   ]
  },
  {
   "title": "Top 10 tags for the past week",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, search_criteria{ctype=\"tag\"})"
    }
   ]
  },
  {
   "title": "Top 10 platforms for the past week",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, search_criteria{ctype=\"platform\"})"
    }
   ]
  },
  {
   "title": "Top 10 cloud platforms for the past week",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, search_criteria{ctype=\"cloud_platform\"})"
    }
   ]
  },
  {
   "title": "Raw search data - 'search' metric",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "search" }
   ]
  },
  {
   "title": "Raw search data - 'search_criteria' metric",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "search_criteria" }
   ]
  }
 ]
}