---
- name: Confirm the web server up
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    galaxy_host: 0.0.0.0
    galaxy_port: 8000

  tasks:
    - name: Wait for server to start
      wait_for:
        timeout: 300

    - name: Access the home page
      uri:
        url: "http://{{ galaxy_host }}:{{ galaxy_port }}"
        return_content: true
      register: homeout

    - name: Assert expected output found
      assert:
        that:
          - "'<title>Ansible Galaxy</title>' in homeout.content"
