# setup_galaxy.yml

- name: Deploy settings file
  template:
    src: /src/settings/settings_develop.py.j2
    dest: /etc/galaxy/settings.py
    owner: "{{ galaxy_user }}"
    group: root
    mode: 0660

- name: Create the SECRET_KEY file
  command: /venv/bin/python -c "import uuid; file('/etc/galaxy/SECRET_KEY', 'wb').write(uuid.uuid4().hex)"
  args:
     creates: /etc/galaxy/SECRET_KEY

- name: Adjust SECRET_KEY permissions
  file:
    path: /etc/galaxy/SECRET_KEY
    state: file
    owner: root
    group: root
    mode: 0660

- name: Build static assets
  command: /venv/bin/python manage.py collectstatic --noinput
  args:
    chdir: /galaxy

# FIXME(cutwater): This is workaround for lacking sudo in centos cointaner
- name: Change ownership of logs and static assets
  file:
    path: "{{ item }}"
    owner: "{{ galaxy_user }}"
    recurse: true
  with_items:
    - /galaxy_logs
    - /var/lib/
