# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_github_attrs'),
        ('main', '0090_issue_tracker_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_user',
        ),
    ]
