# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_github_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_user',
        ),
    ]
