# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181011_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notify_author_release',
            field=models.BooleanField(
                default=True,
                help_text="Notify me when an author I'm following creates" +
                " new content."
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notify_content_release',
            field=models.BooleanField(
                default=True,
                help_text="Notify me when a new release is available for " +
                "content I'm following."
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notify_galaxy_announce',
            field=models.BooleanField(
                default=True,
                help_text="Notify me when there is a Galaxy announcement"
            ),
        ),
    ]
