---
name: Integration
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # - name: Update apt
      #  run: sudo apt -y update

      # - name: Install LDAP requirements
      #  run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: Install docker-compose
        run: pip3 install --upgrade docker-compose
