---
name: Lint
on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: install requirements
        run: pip install -r requirements/dev-requirements.txt

      - name: python lint
        run: make test/flake8

      - name: yaml lint
        run: make test/yamllint

      # - name: javascript lint
      #  run: make test/jslint

      # - name: javascript prettier lint
      #  run: make test/prettier
